export { default as RobotMan } from './1RobotMan'
export { default as BeerHere } from './2BeerHere'
export { default as ImageBoard } from './3ImageBoard'
export { default as FightGame } from './4FightGame'
export { default as About } from './About'